### ISSUE TITLE
Add interval backups not subject to "BackupsToKeep"

### ISSUE THREAD

**Issue by grbray** [clarkx86/vellum#19]
Depending on the interval and the value that "BackupsToKeep" is set to, you could very well end up with only 6 hours of backups.  It'd be nice to have a set schedule (every 6 hours?) for a specified number of Days to keep backups for.  Not dissimilar to a daily full and incrementals.

Day
00:00 - Full
15-60m Interval Backups
06:00 - Full
15-60m Interval Backups
12:00 - Full
15-60m Interval Backups
18:00 - Full
15-60m Interval Backups

Week:
Day 1: 00:00 Full
Day 2: 00:00 Full
Day 3: 00:00 Full
Day 4: 00:00 Full
Day 5: 00:00 Full
Day 6: 00:00 Full
Day 7: 00:00 Full
Day 7: Schedule Above

**Comment by clarkx86** [comment]
Added with [`v1.3.0 beta`](https://github.com/clarkx86/vellum/releases/tag/v1.3.0-beta) (https://github.com/clarkx86/vellum/commit/5d46063ec75b2083e50f8cf0bdcaf1ef6a9ffa3b)
